{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kuview.clusterRoleName" . }}
  labels:
    {{- include "kuview.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - pods
  - pods/log
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups: ["discovery.k8s.io"]
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
{{- end }}
