{{- if .Values.ingress.enabled -}}
apiVersion: {{ include "kuview.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "kuview.fullname" . }}
  labels:
    {{- include "kuview.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and (.Values.ingress.className) (include "kuview.ingress.isStable" .) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if (include "kuview.ingress.supportsPathType" $) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if (include "kuview.ingress.isStable" $) }}
              service:
                name: {{ include "kuview.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
              {{- else }}
              serviceName: {{ include "kuview.fullname" $ }}
              servicePort: {{ $.Values.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
